# IMPORTANT: Nach Age-Key-Generierung muss hier der Public Key eingetragen werden
# age-keygen -o ~/.config/sops/age/keys.txt
# Dann den Public Key hier eintragen:
keys:
  - &achim_mac YOUR_AGE_PUBLIC_KEY_HERE

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *achim_mac
